[build]
  command = "npx vite build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
external_node_modules=["drizzle-orm", "postgres"]
node_bundler = "esbuild"